### ISSUE TITLE
`ReferenceError: process is not defined` for `process.env.DEBUG`

### ISSUE THREAD

**Issue by chmanie** [PiwikPRO/react-piwik-pro#12]
I am trying to integrate this library with [docusaurus](https://docusaurus.io/), but without any luck. After building and running it in the browser I am getting the message

`ReferenceError: process is not defined`, which is true for in-browser processes. It seems that in some environments `process.env.XXX` is replaced by webpack but not in my case. Could you try to make this more portable to other environments?

It's this line here: https://github.com/PiwikPRO/react-piwik-pro/blob/1aeee733eebb17930be3948c140406b08b62c4fb/src/core/index.ts#L34

**Comment by dkrzysztof** [comment]
I also run into the same issue, but in my case it was because I migrated from CRA to vite.
This helped me: https://github.com/vitejs/vite/issues/1973

**Comment by Nubebuster** [comment]
The best fix would probably be to have the debug flag be in the initialize function. It should be an optional parameter defaulting to false in order to maintain backwards compatibility.

I've fixed the issue by setting the IS_DEBUG to true using patch-package but this is not a good solution as I have to change the patch when I build to have debug be false.

**Comment by thomasm0** [comment]
Looks like this is resolved, thanks for the fix
